name: integration-tests

on: pull_request

jobs:
  test:
    name: 'node ${{ matrix.node }} ${{ matrix.os }} '
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 10]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: npm i -g yarn
      - run: yarn --frozen-lockfile
      - run: yarn generateSitemap
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: yarn start
          headless: true
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
