name: integration-tests
on: pull_request
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
         run: yarn
      - name: GenerateSiteMap
        run: babel-node scripts/generateSitemap/
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: yarn start
          headless: true
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
