name: integration-tests
on: pull_request
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: yarn install, and generateSiteMap
      run: |
        yarn
        yarn generateSiteMap
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: yarn start
          headless: true
          config: pageLoadTimeout=100000
